package com.chobichokro.models;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Document(collection = "reviews")
public class Review {
    @Id
    private String id;

    private String movieId;
    private String userId;
    private String theatreId;
    private String opinion;

    private double sentimentScore; // will be generated by our future ai model
}
